  [firebase_config] 
  type = "service_account"
  project_id = "sgamoffice"
  private_key_id = "253915b05b9e2eed6756209d335efd3f79aafde0"
  private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC6DpKQmzblDYYA
28U8WcQdV2vXRGcywY7PSIadzAX1y9obrImlwhOnBEtV0z2X3RlgsI3dsfxQK93b
8VcRsDtxL2eyfiLc+Gj2QltsFI6LmS27LmDJLwOuMd69yhrpf+V0QbmrmaJWQjb7
QRh0fCcX42ZHhGM6/+BnKLsviwiHdRdIqeGdaUr+lViZNm8bqAD8jiQE5xD52YZ7
AU66EEKOCtQrIIVjrBBvmrjzqwyawxgqqBhyBUa4aAHad5q32tkPkGFosQvhx6I/
CDe1HMFRsYtOMcFNCFSWAjMr9INKfKPwlVfFmALQgEcCvP+R1ieJ74dCmDtYQRAD
3PSGCo+RAgMBAAECggEAEXcz/MFnUS/4bfzzeld6ZJ874z67ec0n+u8l3OsFvbXL
1Rh4qO/rsJxjdoxwjiCeJOCaBq9SPlPp3R9eEy3iHJ1MvJmg6/GhR8nBo4cX/QSN
gZJoWUZxr+DkVhhid5wvFd9kHrbawYJwfxxUn322nURWaf0EZCnYPtLY5I0GiVGU
aD1PAZ+5/zXY5ystJYGYjFtDIiFpSxUIAGvjIkwT4T9t/Z46EIDFMz0Ef7e0DIqi
v6Px3EekY6VdBr2+fwzn8rYORU6fQPCQ9bTjgU872VS6+HeeFvdWWTAerlK8fEnN
gy9n1NxKgUVG5fex/FXoSBy7mK0eEwAdqfe+1TvdyQKBgQDnsw1gv+hDx2/ZC8/d
AZ8r4Cp0Ebzv0ZwybE0L63+ALMd4eBN1wOxDXOrxL1S5hoFLwgFTuRI8enuC8dsl
peZUJ4hSPSOvVEQpz6sE/Imdr09BT5CEAOJ++Dh6w24JUBJiOrzQYoIYxIUKu8/K
5Vlk1CdugLMt7af1fraebyxH6QKBgQDNkg4SdkQpMvs8povgxskYxf2f8boj4g2g
pUfNmZxt37voWELPfgNVYHMhxLFhaMs1diQjmm6tP6qLZe8lNdloxE7Ha/iyO9kJ
3zedL8A+rIoBVR8ExmPlQDm74p9bmHBZxdP+FBCxP+KoISOqvDCV6hI9bnMFWWeQ
NGqibT7paQKBgQCVc7BAZOkLtzwVE4Jrux0RrxGTNtHZGyqWd7cm5iui4L91nHZo
8R00wl2lXvNWjEUgOa6jc3Ao5JSAvUKvQRiV1b4f1eILuN4S3iohGEgoFymXJhxA
mVV/stqzjRWQGj8Rb3PVMoVaNoDekJCS/mcwG4ynwYpSKMa7GpXvEiTM6QKBgQCY
57mV2+gpKOWdIFhM8i9kQOi8zoVg6WSviCDXehnT1CYl1Xikc5uxJpOcm3xA8zyr
YFvTK6yFKyUEmOZ/rAUxm0rppJMQp9lxMVphjcIWHCpugU0YNSTawaHv8coMzF9N
NwvPIkekP9usqTGpbl9JMxksHnppkS2qIoLqnA2+eQKBgQCQ/+H2lWPQz9mWCHMY
3o12Dsgl/5IL5CWMsaBfYeie5w4LJXFuw4zXAX28YimodqLVJynWB82HXDIAffdT
eRsT+eGs0rYAczrs9J1lAkYyTqkWfZdjU7MG74WTLm7DpNiu08DDZj7UjwDvaY9A
blj8OR/s/Fl2YZjMaPuuV2sKKw==
-----END PRIVATE KEY-----"""
  client_email = "firebase-adminsdk-fbsvc@sgamoffice.iam.gserviceaccount.com"
  client_id = "114050262389212474997"
  auth_uri = "https://accounts.google.com/o/oauth2/auth"
  token_uri = "https://oauth2.googleapis.com/token"
  auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
  client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40sgamoffice.iam.gserviceaccount.com"
  universe_domain = "googleapis.com"
  [app_auth]
  username = "admin"  
  password = "Sgam@4321"
